# Generated by Django 3.1.7 on 2021-03-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('main_image', models.ImageField(null=True, upload_to='')),
                ('content', models.TextField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('PU', 'published'), ('DR', 'DRAFT')], max_length=2, null=True)),
            ],
        ),
    ]
