# Generated by Django 3.1.7 on 2021-03-13 11:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
