# Generated by Django 3.1.7 on 2021-03-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210314_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('PUB', 'published'), ('DRA', 'draft')], default='DRA', max_length=3),
        ),
    ]
