# Generated by Django 3.1.7 on 2021-03-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210314_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('PUB', 'Published'), ('DRA', 'Draft')], default='DRA', max_length=3),
        ),
    ]
